### ISSUE TITLE
在集群中测试发现的问题

### ISSUE THREAD

**Issue by crazy-dog-zheng** [eosiosg/nodeos-tps#10]
- [X] 不稳定，只有直接连接的节点trxs量大(1300-1500)，其它节点每个块只有平均100左右，所以
  - 需要支持同时连接到多个节点( https://github.com/eosiosg/nodeos-tps/issues/8)
  - sendout需要支持buffer缓存(https://github.com/eosiosg/nodeos-tps/issues/9)
- [X] 在发送几十万(这个数据是大概估计的)transaction的时候，会报错，这个问题暂时不影响当前使用，因为已经设置了重连
![image](https://user-images.githubusercontent.com/5662375/60272476-d3a31c80-9926-11e9-9825-73909874e01d.png)
- [X] 加压的时候会导致latency很高(6000ms-8000ms)，可能是因为国内连接国外网络不好的原因
      * 这个已经确认是因为我压测的节点是(virginiab-z)，但是我在本机观测的(网络状况不好)
      * 压测的同时，观测virginiab-z的日志，时延就很小
- [X] 需要提供一个检测账户是否存在、CPU/NET/MEM资源是否充分、以及转账是否能成功的脚本
      * 在新的issue https://github.com/eosiosg/nodeos-tps/issues/14 中
- [X] 在nodeos-tps连接上peer-boscore-lib-testnet-2-ali-us-virginiab-z.keosd.io就直接报错
![image](https://user-images.githubusercontent.com/5662375/60414719-96cb7400-9c0b-11e9-9bc4-4100a3b396b2.png)
    -  我刚才又重新测试了一下，猜想是这个节点的环境问题，因为nodeos-tps连接其它节点时没有遇到类似问题，此问题需要定位。
    - 此问题目前无法复现了
    - 此问题到目前一直没有浮现(之前是必现)，可认为已经解决
- [X] 发现一个新的特征，在过压的场景下，事务的并发能力会逐渐趋向不稳定(状态变化：(latency升高，trxs为0)，然后latency在3000ms左右会一下子下降到40～80ms，trxs变得正常(Debug下100左右)，如此循环)
      * 过压情况下出现这个是正常的
@qianxiaofeng @oldcold @Frank-AFN

**Comment by ZSmartDog** [comment]
在nodeos-tps连接上peer-boscore-lib-testnet-2-ali-us-virginiab-z.keosd.io就直接报错
![image](https://user-images.githubusercontent.com/5662375/60414719-96cb7400-9c0b-11e9-9bc4-4100a3b396b2.png)

我刚才又重新测试了一下，猜想是这个节点的环境问题，因为nodeos-tps连接其它节点时没有遇到类似问题，此问题需要定位。

**Comment by crazy-dog-zheng** [comment]
开启debug模式之后，tps只有100左右；而debug模式关闭之后性能有较明显的提升

**Comment by qianxiaofeng** [comment]
debug模式跟release本身差距很大 , 这个是已知的, debug版本测试的时候不能压的太大, 可以类似等比的粗略比较

**Comment by crazy-dog-zheng** [comment]
所以我最开始测试发现的第一个问题就可以解释了，即：“不稳定，只有直接连接的节点trxs量大(1300-1500)，其它节点每个块只有平均100左右”；

我那天测试的时候本地用的BP是Release版本，集群上用的是Debug版本，所以轮到我本地的BP节点出块的时候TPS能到1000多，但是其它节点出块的时候TPS只有100左右。

**Comment by crazy-dog-zheng** [comment]
commit 4e99a63f01559836f01c5c3a29696e374b12f768

-------在发送几十万(这个数据是大概估计的)transaction的时候，会报错，这个问题暂时不影响当前使用，因为已经设置了重连

此问题已经解决

**Comment by crazy-dog-zheng** [comment]
这次使用boost asio遇到的几个问题：
1. async_write_some不能保证一次性把数据写出，在complete_handler第二个参数（bytes_transferred）会传入实际写出的字节，但是不能在complete_handler中递归调用处理(因为无法保证数据的顺序性)。所以从我的角度将，async_write_some基本不可用，暂时没有发现什么技巧可以让它可用。 [存疑，有可能是因为我开始的时候使用了for循环调用async_write的原因]
1. async_write使用默认方式，也无法保证一次性写出数据，即：
    ```c++
     boost::asio::async_write(s, boost::asio::buffer(data, size), handler);
    ```
    但是有带有completion_condition回调的重载函数，参考: https://www.boost.org/doc/libs/1_67_0/doc/html/boost_asio/reference/async_write/overload2.html
    completion_condition写成如下，可以让async_write顺序的(可能一次或者多次)把数据发送出去:
    ```c++
    completion_condition=[bufferLen](const boost::system::error_code& error,   std::size_t bytes_transferred) {
        return (ec || (bufferLen <= bytes_transferred)) ? 0:(bufferLen - bytes_transferred);
    }
    ```
1. 不要使用循环调用async_read*/async_write*系列函数，而是在complete_handler中递归调用，不然数据量稍微大一些就会出现数据截断，甚至core dump.
1. 在调用异步函数的时候，需要保证数据在发送出去之前数据未被释放掉(async_write典型的错误是，传入局部变量的指针或者引用)

**Comment by crazy-dog-zheng** [comment]
新的测试情况(nodeos-tps和nodeos通过公网连接)：

每间隔X发送一次(两个transaction) | 稳定情况 | trxs(个) | trxs峰值 | latency(ms) | 备注
-- | -- | -- | -- | -- | --
100ms | 稳定 | 10 | 12 | 130~140 |  
10ms | 稳定 | 85~95 | 128 | 130~200 |  
7.5ms | 较稳定 | 110~125 | 647 | 250~1500 | 有开始出现较高的latency
5ms | 较稳定 | 120～260 | 1013 | 250~4000 | 同上
2.5ms | 较稳定 | 170～600 | 1043 | 1700～7000 | 有一次测试：一段时间后tps报错read message error，然后进行了重连，不过服务器端没报错，猜测是tps工具解析pbft message的问题
2ms | 较稳定 | 200～700 | 1083 | 2100～8500 | 存在几次tps工具启动之后无反应
1.5ms | 较稳定 | 300～900 | 1149 | 同上 |  
1ms | 不太稳定 | 400~1000 | 1387 | 同上 | 存在几次tps工具启动之后无反应服务器日志中有较多的switch fork
0.75ms | 不太稳定 | 同上 | 1255 | 同上 | 服务器日志中有较多的switch fork
0.5ms | 不稳定 | 同上 | 1117 | 4000～11000 | 服务器日志中频繁switch fork

加压tps上不去，且不稳定，可能的两个原因：
   - [X] 发送出去的数据没有做合并，每个transaction都是单独发的数据，导致发送次数较多(每次发送又有时延)。TPS加压上不去的原因已经找到，且解决，参考：https://github.com/eosiosg/nodeos-tps/issues/12
   - [X] 只向一个节点加压导致tps必然上不去。解决方案：向多个节点广播
      * 有新的issue跟踪 https://github.com/eosiosg/nodeos-tps/issues/8
