### ISSUE TITLE
error in read, Connection reset by peer

### ISSUE THREAD

**Issue by crazy-dog-zheng** [eosiosg/nodeos-tps#15]
在运行过程中，tps工具会报此错误，但是服务器端为报错

初步估计是更新了bos pbft的某些message，字段没有完全对应上，待排查

**Comment by oldcold** [comment]
> 在运行过程中，tps工具会报此错误，但是服务器端为报错
> 
> 初步估计是更新了bos pbft的某些message，字段没有完全对应上，待排查

pbft消息解析错误不会造成对方断连，只有可能是你这边断连。
