### ISSUE TITLE
BOS网络层pbft和transaction message统计

### ISSUE THREAD

**Issue by Frank-AFN** [eosiosg/nodeos-tps#17]
需求: pbft message   network layer统计, 参数:  peer:   time_granularity, 可以配置多个connection

| connection: peer.eosio.sg:8888 | 消息数量 | 消息字节数 | 消息数量在pbft消息数量占比 | 消息字节在pbft消息字节占比 | 消息数量在总消息数量占比 | 消息字节在总消息字节占比 |
|--------------------------------|----------|------------|----------------------------|----------------------------|--------------------------|--------------------------|
| pbft prepare message           |          |            |                            |                            |                          |                          |
| pbft commit meesage            |          |            |                            |                            |                          |                          |
| pbft view change message       |          |            |                            |                            |                          |                          |
| pbft new view message          |          |            |                            |                            |                          |                          |
| pbft checkpoint message        |          |            |                            |                            |                          |                          |
| pbft stable checkpoint message |          |            |                            |                            |                          |                          |
| total pbft message             |          |            |                            |                            |                          |                          |
| total messages                 |          |            |                            |                            |                          |                          |

需求待定:

需求: transaction   message network layer统计, transaction可以配置filter,   某个合约下某个action和某个账户相关的transaction过滤出来, 参数:   peer:contract:action:account_name,    peer: time_granularity 用: 分隔, 可以配置多个filter.

| connection: peer.eosio.sg:8888                   | trx数量 | trx字节数 | trx数量在总消息数量占比 | trx字节在总消息字节占比 |
|--------------------------------------------------|---------|-----------|-------------------------|-------------------------|
| transaction: eosio.token: transfer: perfectfrank |         |           |                         |                         |
| transaction: findexfindex: buyorder: pefectfrank |         |           |                         |                         |
| total message                                    |         |           |                         |                         |

**Comment by crazy-dog-zheng** [comment]
这个已经使用了grafana+influxdb+nodeos-tps stat，使用起来更加方便，功能更强大[点我](http://monitor.enjoyshare.net)

用户名密码:boscore/boscore
