### ISSUE TITLE
write build script

### ISSUE THREAD

**Issue by crazy-dog-zheng** [eosiosg/nodeos-tps#2]
1. auto download fc, libboost and so on
2. check out to right version
3. correctly compile.

**Comment by crazy-dog-zheng** [comment]
1. 我现在mac的本地编译环境是坏的，没办法测试编译脚本。
1. 我制作了dockerfile， 大家可以使用docker。
1. mac上本地调试可以参考dockerfile安装软件
1. 使用参考如下
```bash
# compile nodeos-tps
cd nodeos-tps
sudo docker build -t nodeos-tps . 

# direct run nodeos-tps
# check nodeos run on <ip>:<port> before run nodeos-tps
sudo docker run --net=host --name=tps -d nodeos-tps /usr/bin/nodeos-tps <ip>  <port>
# example: sudo docker run --name=tps -d nodeos-tps /usr/bin/nodeos-tps 127.0.0.1 9876
sudo docker logs tps # 查看接受到的各种message
```
![image](https://user-images.githubusercontent.com/5662375/59827079-5269e980-936a-11e9-839c-a89a36697080.png)

**Comment by qianxiaofeng** [comment]
1. auto download fc 用cmake和git submodule来控制, boost使用最新版本
2. docker 不要使用sudo,  在安装完docker后,按照下面链接执行配置
https://docs.docker.com/install/linux/linux-postinstall/
3. 本地开发环境compile的问题是什么

**Comment by crazy-dog-zheng** [comment]
这几个问题当前影响不太大(毕竟是在测试环境上运行)，暂时先处理优先级更高的其它issue

**Comment by crazy-dog-zheng** [comment]
现在能使用docker 进行build，参考[点我](https://github.com/eosiosg/nodeos-tps/wiki/nodeos-tps%E5%B7%A5%E5%85%B7%E7%BC%96%E8%AF%91%E6%8C%87%E5%8D%97)
