### ISSUE TITLE
support send specific transaction

### ISSUE THREAD

**Issue by crazy-dog-zheng** [eosiosg/nodeos-tps#6]
- [x] packed_transaction生成(可能有较多坑)
  * [x] 签名代码移植
  * [x] 创建测试账号(是事务的一种)
  * [x] 转账(也是一种事务)
  * [X] 自动安装eosio.token和eosio.system合约(计划放到bash脚本中完成) 已有issue跟踪 https://github.com/eosiosg/nodeos-tps/issues/10
- [X] packed_transaction发送
  * [x] 打包链上信息
    - [x] 获取chain_id
    - [x] 获取head_block_time
    - [x] 获取head_block_id
  * [x] 事务签名
  * [x] 事务压缩
  * [x] 事务发送
- [X] 支持从配置文件读取配置信息(当前非必须) 已有issue跟踪 https://github.com/eosiosg/nodeos-tps/issues/7

1. 乐观情况1和2本周能做完，如果遇到问题取决于问题解决的时间
1. 3是一个持续优化的过程

**Comment by crazy-dog-zheng** [comment]
@qianxiaofeng @oldcold @Frank-AFN 现在遇到比较难受的问题打包链上信息( 获取chain_id、 获取head_block_time、 获取head_block_id)代码上去调用了chain_plugin，需要和fork_db打交道。其中chain_id可以写死或者从命令行读如，但是head_block_time、 head_block_id比较困难，这块需要一些协助

**Comment by qianxiaofeng** [comment]
通过收到的块信息来实时填入

**Comment by crazy-dog-zheng** [comment]
commit 6178b23a9cf4cd7c2767c02af3791ac223a84f7f

已经可以发送eosio.token的transfer，当前本地测试单个block只能放入不到1500个transfer。初步估计是因为没有作send_out_buffer的原因。send_out_buffer弄好，明天可以接入Frank手里的测试环境进行测试
